const $=s=>document.querySelector(s), appEl=$('#app'); let app,auth,db,currentUser,userDoc=null,state={groups:[],students:[],teachers:[],subjects:[],sessions:[],attendance:[]};
const cfg=window.FIREBASE_CONFIG; if(!cfg) alert('Falta config.js'); firebase.initializeApp(cfg); auth=firebase.auth(); db=firebase.firestore();
const C={users:db.collection('users'),groups:db.collection('groups'),students:db.collection('students'),subjects:db.collection('subjects'),sessions:db.collection('sessions'),attendance:db.collection('attendance'),grades:db.collection('grades'),observations:db.collection('observations'),settings:db.collection('settings')};
const today=()=>new Date().toISOString().slice(0,10), nowTime=()=>new Date().toTimeString().slice(0,5), id=()=>Math.random().toString(36).slice(2,10), esc=s=>(s??'').toString().replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
async function qs(col){const r=await col.get();return r.docs.map(d=>({id:d.id,...d.data()}));} async function load(){[state.groups,state.students,state.subjects,state.teachers,state.sessions,state.attendance]=await Promise.all([qs(C.groups),qs(C.students),qs(C.subjects),C.users.where('role','==','teacher').get().then(r=>r.docs.map(d=>({id:d.id,...d.data()}))),qs(C.sessions),qs(C.attendance)]);}
async function hasAdmin(){const r=await C.users.where('role','==','admin').limit(1).get();return !r.empty}
auth.onAuthStateChanged(async u=>{currentUser=u;if(location.search.includes('register=')){showStudentRegister();return} if(!u){(await hasAdmin())?showLogin():showSetup();return} const d=await C.users.doc(u.uid).get(); userDoc=d.exists?d.data():null; if(!userDoc){showLogin('Tu cuenta no tiene rol en Firestore. Pide al administrador que la registre.');return} await load(); showShell();});
function logo(){return '<img src="assets/logo_big.png" alt="BIG"><h1>SIGE BIG</h1><p>Sistema Integral de Gestión Escolar</p>'}
function showSetup(msg=''){appEl.innerHTML=`<div class="login"><section class="brand">${logo()}<p>Primer ingreso: crea el administrador principal.</p></section><section class="card"><h2>Configuración inicial</h2>${msg?`<div class="banner">${msg}</div>`:''}<label>Nombre completo</label><input id="suName" placeholder="Ej. Eduardo Chávez"><label>Correo</label><input id="suEmail" type="email"><label>Contraseña</label><input id="suPass" type="password" placeholder="mínimo 6 caracteres"><button onclick="createAdmin()">Crear administrador</button><p class="small">Si el correo ya existe en Firebase, usa otro correo o inicia sesión.</p></section></div>`}
async function createAdmin(){try{const name=$('#suName').value.trim(),email=$('#suEmail').value.trim(),pass=$('#suPass').value;if(!name||!email||pass.length<6) return alert('Completa los datos.');const cred=await auth.createUserWithEmailAndPassword(email,pass);await C.users.doc(cred.user.uid).set({name,email,role:'admin',createdAt:Date.now()});}catch(e){showSetup('No se pudo crear: '+e.message)}}
function showLogin(msg=''){appEl.innerHTML=`<div class="login"><section class="brand">${logo()}<p>Acceso seguro con Firebase</p></section><section class="card"><h2>Iniciar sesión</h2>${msg?`<div class="banner">${msg}</div>`:''}<label>Correo electrónico</label><input id="email" type="email"><label>Contraseña</label><input id="pass" type="password"><button onclick="login()">Entrar</button><button class="secondary" onclick="resetPass()">Recuperar contraseña</button></section></div>`}
async function login(){try{await auth.signInWithEmailAndPassword($('#email').value.trim(),$('#pass').value)}catch(e){alert(e.message)}} async function resetPass(){const email=$('#email').value.trim();if(!email)return alert('Escribe el correo.');await auth.sendPasswordResetEmail(email);alert('Correo de recuperación enviado.')} function logout(){auth.signOut()}
function menuItems(){const r=userDoc.role; const all=[['dash','Inicio'],['admin','Administración'],['students','Alumnos'],['teachers','Profesores'],['groups','Grupos'],['attendance','Asistencia QR'],['reports','Reportes'],['grades','Calificaciones'],['obs','Observaciones'],['family','Portal familiar'],['config','Configuración']];const allow={admin:all.map(x=>x[0]),teacher:['dash','attendance','reports','grades','obs'],parent:['family'],student:['family'],school:['dash','students','reports','grades','obs']};return all.filter(x=>(allow[r]||[]).includes(x[0]));}
function showShell(view='dash'){appEl.innerHTML=`<div class="layout"><aside class="side"><div style="display:flex;gap:10px;align-items:center"> <img src="assets/logo_big.png"><h2>Bachillerato Integral Guanajuato</h2></div><div class="nav">${menuItems().map(m=>`<button data-v="${m[0]}" onclick="showShell('${m[0]}')">${m[1]}</button>`).join('')}</div><hr><p>${esc(userDoc.name)}<br><span class="small">${userDoc.role}</span></p><button class="secondary" onclick="logout()">Cerrar sesión</button></aside><main class="main"><div class="top"><h1>${title(view)}</h1><span>${new Date().toLocaleDateString('es-MX')}</span></div><div id="view"></div></main></div>`;document.querySelector(`[data-v=${view}]`)?.classList.add('active');render(view)}
function title(v){return {dash:'Panel de control',admin:'Administración',students:'Alumnos',teachers:'Profesores',groups:'Grupos',attendance:'Asistencia QR',reports:'Reportes',grades:'Calificaciones',obs:'Observaciones',family:'Portal familiar',config:'Configuración'}[v]||'SIGE BIG'}
function render(v){({dash:dashboard,admin:admin,students:students,teachers:teachers,groups:groups,attendance:attendance,reports:reports,grades:grades,obs:observations,family:family,config:config}[v]||dashboard)()}
function dashboard(){let present=state.attendance.filter(a=>a.date==today()).length;$('#view').innerHTML=`<div class="grid"><div class="card metric"><span>Alumnos</span><br><b>${state.students.length}</b></div><div class="card metric"><span>Profesores</span><br><b>${state.teachers.length}</b></div><div class="card metric"><span>Grupos</span><br><b>${state.groups.length}</b></div><div class="card metric"><span>Asistencias hoy</span><br><b>${present}</b></div></div><div class="grid3" style="margin-top:18px"><div class="card"><h3>Asistencia QR</h3><p>Genera sesiones con QR dinámico.</p></div><div class="card"><h3>Calificaciones</h3><p>Captura parciales por materia.</p></div><div class="card"><h3>Portal familiar</h3><p>Consulta asistencia, notas y observaciones.</p></div></div>`}
function admin(){let html=`<div class="grid2"><div class="card"><h3>Alta rápida</h3><button onclick="seedBase()">Crear 6 grupos base</button><button onclick="showShell('teachers')">Registrar profesores</button><button onclick="showShell('students')">Registrar alumnos</button></div><div class="card"><h3>Estado</h3><p>Firebase conectado. Usuarios por rol desde Firestore.</p><p class="small">El administrador puede crear docentes, grupos, materias y alumnos sin tocar Firebase.</p></div></div>`;$('#view').innerHTML=html}
async function seedBase(){for(const g of ['1A','1B','2A','2B','3A','3B']) await C.groups.doc(g).set({name:g}); await load();alert('Grupos creados/actualizados')}
function students(){let rows=state.students.map(s=>`<tr><td>${esc(s.matricula||s.id)}</td><td>${esc(s.name)}</td><td>${esc(s.group)}</td><td><button class="danger" onclick="del('students','${s.id}')">Borrar</button></td></tr>`).join('');$('#view').innerHTML=`<div class="grid2"><div class="card"><h3>Agregar alumno</h3><input id="stMat" placeholder="Matrícula"><input id="stName" placeholder="Nombre completo"><select id="stGroup">${groupOpts()}</select><input id="stParent" placeholder="Correo tutor opcional"><button onclick="addStudent()">Guardar alumno</button><hr><h4>Importar desde Excel</h4><input type="file" id="xl" accept=".xlsx,.xls"><button class="secondary" onclick="importStudents()">Importar</button><p class="small">Columnas recomendadas: matricula, nombre, grupo, tutorEmail.</p></div><div class="card"><h3>Alumnos</h3><table><tr><th>Matrícula</th><th>Nombre</th><th>Grupo</th><th></th></tr>${rows}</table></div></div>`}
function groupOpts(){return state.groups.map(g=>`<option value="${esc(g.name||g.id)}">${esc(g.name||g.id)}</option>`).join('')} async function addStudent(){const matricula=$('#stMat').value.trim()||id(), name=$('#stName').value.trim(), group=$('#stGroup').value, parentEmail=$('#stParent').value.trim();if(!name)return alert('Falta nombre');await C.students.doc(matricula).set({matricula,name,group,parentEmail});await load();students()}
async function importStudents(){const f=$('#xl').files[0];if(!f)return;const data=await f.arrayBuffer();const wb=XLSX.read(data);const json=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);for(const r of json){const matricula=(r.matricula||r.Matricula||r.MATRICULA||r['Matrícula']||id()).toString();const name=r.nombre||r.Nombre||r.NOMBRE;const group=r.grupo||r.Grupo||r.GRUPO;if(name&&group) await C.students.doc(matricula).set({matricula,name,group,parentEmail:r.tutorEmail||r.Tutor||''});}await load();students()}
function teachers(){let rows=state.teachers.map(t=>`<tr><td>${esc(t.name)}</td><td>${esc(t.email)}</td><td>${esc((t.groups||[]).join(', '))}</td><td><button class="danger" onclick="del('users','${t.id}')">Borrar rol</button></td></tr>`).join('');$('#view').innerHTML=`<div class="grid2"><div class="card"><h3>Registrar profesor</h3><input id="teName" placeholder="Nombre"><input id="teEmail" type="email" placeholder="correo"><input id="tePass" type="password" placeholder="contraseña inicial"><label>Grupos asignados</label>${state.groups.map(g=>`<label><input type="checkbox" class="tg" value="${g.name||g.id}" style="width:auto"> ${g.name||g.id}</label>`).join('')}<button onclick="addTeacher()">Crear profesor</button><p class="small">Se crea en Authentication y en Firestore.</p></div><div class="card"><h3>Profesores</h3><table><tr><th>Nombre</th><th>Correo</th><th>Grupos</th><th></th></tr>${rows}</table></div></div>`}
async function addTeacher(){try{const name=$('#teName').value.trim(),email=$('#teEmail').value.trim(),pass=$('#tePass').value||'Big2026*',groups=[...document.querySelectorAll('.tg:checked')].map(x=>x.value);if(!name||!email)return alert('Completa datos');const cur=auth.currentUser;const cred=await auth.createUserWithEmailAndPassword(email,pass);await C.users.doc(cred.user.uid).set({name,email,role:'teacher',groups});await auth.signInWithEmailAndPassword(cur.email,prompt('Por seguridad Firebase cerró la sesión. Escribe tu contraseña de administrador para volver:'));await load();teachers()}catch(e){alert(e.message)}}
function groups(){let rows=state.groups.map(g=>`<tr><td>${esc(g.name||g.id)}</td><td>${esc(g.level||'')}</td><td><button class="danger" onclick="del('groups','${g.id}')">Borrar</button></td></tr>`).join('');$('#view').innerHTML=`<div class="card"><h3>Grupos</h3><input id="gName" placeholder="Ej. 3A"><input id="gLevel" placeholder="Semestre o grado"><button onclick="addGroup()">Agregar grupo</button><table><tr><th>Grupo</th><th>Nivel</th><th></th></tr>${rows}</table></div>`} async function addGroup(){const name=$('#gName').value.trim();if(!name)return;await C.groups.doc(name).set({name,level:$('#gLevel').value.trim()});await load();groups()}
function teacherGroups(){return userDoc.role=='teacher'?(userDoc.groups||[]):state.groups.map(g=>g.name||g.id)}
function attendance(){const opts=teacherGroups().map(g=>`<option>${g}</option>`).join('');$('#view').innerHTML=`<div class="grid2"><div class="card"><h3>Crear sesión de asistencia</h3><label>Grupo</label><select id="asGroup">${opts}</select><label>Hora de inicio</label><input id="asStart" type="time" value="${nowTime()}"><label>Tolerancia en minutos</label><input id="asTol" type="number" value="10"><label>Duración del QR en minutos</label><input id="asDur" type="number" value="30"><button onclick="createSession()">Generar QR</button><div id="qr"></div></div><div class="card"><h3>Registro manual</h3><select id="manGroup" onchange="fillStudentsSelect()">${opts}</select><select id="manStudent"></select><input id="manDate" type="date" value="${today()}"><input id="manTime" type="time" value="${nowTime()}"><button onclick="manualAttendance()">Registrar asistencia manual</button></div></div>`;fillStudentsSelect()}
function fillStudentsSelect(){const g=$('#manGroup')?.value;const sel=$('#manStudent'); if(!sel)return;sel.innerHTML=state.students.filter(s=>s.group==g).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
async function createSession(){const group=$('#asGroup').value,start=$('#asStart').value,tolerance=Number($('#asTol').value),duration=Number($('#asDur').value), sid=id(), expires=Date.now()+duration*60000;await C.sessions.doc(sid).set({group,start,tolerance,duration,expires,date:today(),teacherId:currentUser.uid,teacherName:userDoc.name,createdAt:Date.now()});const url=location.origin+location.pathname+`?register=${sid}`;$('#qr').innerHTML=`<div class="qrbox"><h3>QR de asistencia</h3><canvas id="qrc"></canvas><p class="small">${url}</p></div>`;QRCode.toCanvas($('#qrc'),url,{width:260});await load()}
async function manualAttendance(){const studentId=$('#manStudent').value, date=$('#manDate').value, time=$('#manTime').value, student=state.students.find(s=>s.id==studentId), group=$('#manGroup').value;if(!student)return;await saveAttendance({sessionId:'manual-'+date+'-'+group,student,group,date,time,start:time,tolerance:0,manual:true});alert('Registrado');await load()}
async function showStudentRegister(){await load();const sid=new URLSearchParams(location.search).get('register');const sessDoc=await C.sessions.doc(sid).get();if(!sessDoc.exists){appEl.innerHTML='<div class="card"><h2>Sesión no encontrada</h2></div>';return}const sess={id:sid,...sessDoc.data()};if(sess.expires<Date.now()){appEl.innerHTML='<div class="card"><h2>QR expirado</h2></div>';return}const locked=localStorage.getItem('locked_'+sid);if(locked){appEl.innerHTML=`<div class="login"><section class="brand">${logo()}</section><section class="card"><h2>Asistencia registrada</h2><p>Este dispositivo ya registró asistencia para esta sesión.</p></section></div>`;return}const studs=state.students.filter(s=>s.group==sess.group);appEl.innerHTML=`<div class="login"><section class="brand">${logo()}<h2>${sess.group}</h2></section><section class="card"><h2>Registrar asistencia</h2><p>Selecciona tu nombre.</p><select id="regStudent">${studs.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><button onclick="studentSubmit('${sid}')">Registrar</button></section></div>`}
async function studentSubmit(sid){const sess=(await C.sessions.doc(sid).get()).data(), st=state.students.find(s=>s.id==$('#regStudent').value);await saveAttendance({sessionId:sid,student:st,group:sess.group,date:sess.date,time:nowTime(),start:sess.start,tolerance:sess.tolerance});localStorage.setItem('locked_'+sid,'1');appEl.innerHTML=`<div class="login"><section class="brand">${logo()}</section><section class="card"><h2>Asistencia registrada</h2><p>Gracias, ${esc(st.name)}.</p><p class="small">Ya puedes cerrar esta página.</p></section></div>`}
function status(time,start,tol){const [h,m]=time.split(':').map(Number),[sh,sm]=start.split(':').map(Number), diff=(h*60+m)-(sh*60+sm); if(diff<=0)return 'A'; if(diff<=tol)return 'T'; return 'R'}
async function saveAttendance(o){const docId=`${o.sessionId}_${o.student.id}`;const exists=await C.attendance.doc(docId).get();if(exists.exists) throw alert('Este alumno ya tiene registro.');await C.attendance.doc(docId).set({sessionId:o.sessionId,studentId:o.student.id,studentName:o.student.name,group:o.group,date:o.date,time:o.time,status:status(o.time,o.start,o.tolerance),manual:!!o.manual,createdAt:Date.now()})}
function reports(){const opts=teacherGroups().map(g=>`<option>${g}</option>`).join('');$('#view').innerHTML=`<div class="grid2"><div class="card"><h3>Reporte diario</h3><select id="rGroup">${opts}</select><input id="rDate" type="date" value="${today()}"><button onclick="dailyReport()">Generar</button><button class="secondary" onclick="exportDailyPDF()">Exportar PDF</button><button class="secondary" onclick="exportDailyCSV()">Exportar CSV</button><div id="daily"></div></div><div class="card"><h3>Reporte acumulado</h3><select id="aGroup">${opts}</select><input id="d1" type="date" value="${today()}"><input id="d2" type="date" value="${today()}"><button onclick="accReport()">Generar acumulado</button><button class="secondary" onclick="exportAccPDF()">Exportar PDF</button><button class="secondary" onclick="exportAccCSV()">Exportar CSV</button><div id="acc"></div></div></div>`}
let lastDaily=[],lastAcc={rows:[],dates:[]};function dailyReport(){const g=$('#rGroup').value,d=$('#rDate').value;lastDaily=state.attendance.filter(a=>a.group==g&&a.date==d).sort((a,b)=>a.studentName.localeCompare(b.studentName));$('#daily').innerHTML=tableDaily(lastDaily)} function tableDaily(rows){return `<table><tr><th>Fecha</th><th>Grupo</th><th>Nombre</th><th>Hora</th><th></th></tr>${rows.map(r=>`<tr><td>${r.date}</td><td>${r.group}</td><td>${esc(r.studentName)}</td><td><b class="${r.status=='A'?'green':r.status=='T'?'yellow':'red'}">${r.time}</b></td><td><button class="danger" onclick="del('attendance','${r.id}')">Borrar</button></td></tr>`).join('')}</table>`}
function datesBetween(a,b){let arr=[],d=new Date(a+'T00:00');const end=new Date(b+'T00:00');while(d<=end){arr.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return arr}function accReport(){const g=$('#aGroup').value,dates=datesBetween($('#d1').value,$('#d2').value),studs=state.students.filter(s=>s.group==g).sort((a,b)=>a.name.localeCompare(b.name));const rows=studs.map(s=>({name:s.name,vals:dates.map(d=>state.attendance.some(a=>a.group==g&&a.date==d&&a.studentId==s.id)?'A':'NA')}));lastAcc={group:g,dates,rows};$('#acc').innerHTML=`<table><tr><th>Alumno</th>${dates.map(d=>`<th>${d.slice(5)}</th>`).join('')}</tr>${rows.map(r=>`<tr><td>${esc(r.name)}</td>${r.vals.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</table>`}
function exportDailyCSV(){if(!lastDaily.length)return alert('Genera el reporte primero');downloadCSV('reporte_diario.csv',['fecha,grupo,nombre,hora',...lastDaily.map(r=>`${r.date},${r.group},"${r.studentName}",${r.time}`)].join('\n'))}function exportAccCSV(){if(!lastAcc.rows.length)return alert('Genera el reporte primero');downloadCSV('reporte_acumulado.csv',[['Alumno',...lastAcc.dates].join(','),...lastAcc.rows.map(r=>[`"${r.name}"`,...r.vals].join(','))].join('\n'))}function downloadCSV(name,txt){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/csv'}));a.download=name;a.click()}
function exportDailyPDF(){if(!lastDaily.length)return alert('Genera el reporte primero');const {jsPDF}=window.jspdf,doc=new jsPDF();doc.text('Reporte diario SIGE BIG',14,15);let y=28;lastDaily.forEach(r=>{doc.text(`${r.date}  ${r.group}  ${r.studentName}`,14,y);doc.setFont('helvetica','bold');doc.setTextColor(r.status=='A'?22:r.status=='T'?245:220,r.status=='A'?163:r.status=='T'?158:38,r.status=='A'?74:r.status=='T'?11:38);doc.text(r.time,170,y);doc.setTextColor(0,0,0);doc.setFont('helvetica','normal');y+=8;if(y>280){doc.addPage();y=20}});doc.save('reporte_diario.pdf')}function exportAccPDF(){if(!lastAcc.rows.length)return alert('Genera el reporte primero');const {jsPDF}=window.jspdf,doc=new jsPDF('l');doc.text('Reporte acumulado SIGE BIG - '+lastAcc.group,14,15);let y=26;doc.setFontSize(8);doc.text(['Alumno',...lastAcc.dates.map(d=>d.slice(5))].join('   '),14,y);y+=7;lastAcc.rows.forEach(r=>{doc.text([r.name.slice(0,25),...r.vals].join('   '),14,y);y+=6;if(y>190){doc.addPage();y=20}});doc.save('reporte_acumulado.pdf')}
function grades(){const opts=teacherGroups().map(g=>`<option>${g}</option>`).join('');$('#view').innerHTML=`<div class="card"><h3>Captura de calificaciones</h3><select id="grGroup" onchange="gradeTable()">${opts}</select><input id="grSubject" placeholder="Materia"><button onclick="gradeTable()">Cargar alumnos</button><div id="gradeTable"></div></div>`;gradeTable()}async function gradeTable(){const g=$('#grGroup')?.value;if(!g)return;const studs=state.students.filter(s=>s.group==g);$('#gradeTable').innerHTML=`<table><tr><th>Alumno</th><th>P1</th><th>P2</th><th>P3</th><th>Final</th><th></th></tr>${studs.map(s=>`<tr><td>${esc(s.name)}</td><td><input id="p1_${s.id}" type="number"></td><td><input id="p2_${s.id}" type="number"></td><td><input id="p3_${s.id}" type="number"></td><td><input id="pf_${s.id}" type="number"></td><td><button onclick="saveGrade('${s.id}','${esc(s.name)}')">Guardar</button></td></tr>`).join('')}</table>`}async function saveGrade(sid,name){const subject=$('#grSubject').value||'Materia';await C.grades.doc(`${sid}_${subject}`).set({studentId:sid,studentName:name,group:$('#grGroup').value,subject,p1:val('p1_'+sid),p2:val('p2_'+sid),p3:val('p3_'+sid),final:val('pf_'+sid),updatedAt:Date.now()});alert('Guardado')}function val(i){return Number(document.getElementById(i)?.value||0)}
function observations(){const opts=teacherGroups().map(g=>`<option>${g}</option>`).join('');$('#view').innerHTML=`<div class="card"><h3>Observaciones por estudiante</h3><select id="obGroup" onchange="fillObsStudents()">${opts}</select><select id="obStudent"></select><select id="obType"><option>Académica</option><option>Conducta</option><option>Tareas</option><option>Reconocimiento</option></select><textarea id="obText" placeholder="Escribe la observación"></textarea><button onclick="saveObs()">Guardar observación</button></div>`;fillObsStudents()}function fillObsStudents(){const g=$('#obGroup')?.value,sel=$('#obStudent');if(sel)sel.innerHTML=state.students.filter(s=>s.group==g).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}async function saveObs(){const sid=$('#obStudent').value,st=state.students.find(s=>s.id==sid);await C.observations.add({studentId:sid,studentName:st.name,group:st.group,type:$('#obType').value,text:$('#obText').value,date:today(),teacherName:userDoc.name});alert('Observación guardada')}
async function family(){const email=currentUser?.email||'';const studs=state.students.filter(s=>s.parentEmail==email||s.email==email);$('#view').innerHTML=`<div class="card"><h3>Consulta familiar</h3>${studs.length?studs.map(s=>`<div class="banner"><b>${esc(s.name)}</b> ${esc(s.group)}<br>Asistencias: ${state.attendance.filter(a=>a.studentId==s.id).length}</div>`).join(''):'<p>No hay estudiantes vinculados a este correo. El administrador debe registrar el correo del tutor en el alumno.</p>'}</div>`}
function config(){$('#view').innerHTML='<div class="card"><h3>Configuración</h3><p>Opciones institucionales: horarios, tolerancias, ciclos escolares, logo y escala de calificaciones.</p></div>'}
async function del(col,idv){if(!confirm('¿Borrar registro?'))return;await db.collection(col).doc(idv).delete();await load();showShell(document.querySelector('.nav .active')?.dataset.v||'dash')}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
