const $ = s => document.querySelector(s);
const uid = () => Math.random().toString(36).slice(2,10) + Date.now().toString(36).slice(-4);
const today = () => new Date().toISOString().slice(0,10);
const nowTime = () => new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});
const baseUrl = () => location.href.split('#')[0];
let db=null, online=false, state={user:null,role:null,tab:'dashboard'};
const LS='big_attendance_v2_listas_mayo_agosto_2026';
const APP_VERSION='listas-mayo-agosto-2026';
const defaults=window.INITIAL_DATA || {teachers:[],groups:[],students:[],sessions:[],attendance:[],version:APP_VERSION};
function load(){let d=JSON.parse(localStorage.getItem(LS)||'null'); if(!d || d.version!==APP_VERSION){d=JSON.parse(JSON.stringify(defaults)); save(d);} return d;}
function save(d){localStorage.setItem(LS,JSON.stringify(d));}
let data=load();
function initFirebase(){try{ if(window.FIREBASE_CONFIG && firebase?.apps?.length===0){firebase.initializeApp(window.FIREBASE_CONFIG); db=firebase.firestore(); online=true; $('#modeBadge').textContent='Modo nube'; $('#modeBadge').style.color='#0f766e'; }}catch(e){console.warn(e)}}
initFirebase();
function render(){const hash=new URLSearchParams((location.hash.split('?')[1]||'')); if(location.hash.startsWith('#/student')) return renderStudent(hash.get('session')); if(!state.user) return renderLogin(); const app=$('#app'); app.innerHTML=`<section class="card"><div class="row"><div style="flex:1"><h2>Hola, ${state.user}</h2><p class="muted">${state.role==='admin'?'Administrador':'Maestro'} · ${online?'datos en la nube':'modo local'}</p></div><button class="secondary" onclick="logout()">Salir</button></div></section><div class="tabs">${['dashboard','sesion','asistencia','alumnos','maestros','credenciales','reportes'].map(t=>`<button class="${state.tab===t?'active':''}" onclick="state.tab='${t}';render()">${label(t)}</button>`).join('')}</div><div id="view"></div>`; views[state.tab]();}
function label(t){return {dashboard:'Inicio',sesion:'Generar QR',asistencia:'Asistencia',alumnos:'Alumnos',maestros:'Maestros',credenciales:'Credenciales QR',reportes:'Reportes'}[t]}
function renderLogin(){const app=$('#app'); app.innerHTML=$('#loginTpl').innerHTML; $('#loginBtn').onclick=()=>{state.role=$('#role').value; state.user=$('#username').value.trim()|| (state.role==='admin'?'Administrador':'Maestro'); render();}; $('#studentBtn').onclick=()=>renderStudent(null);}
function logout(){state={user:null,role:null,tab:'dashboard'}; render();}
const teacherObj=()=>data.teachers.find(t=>t.name.toLowerCase()===state.user.toLowerCase()) || data.teachers[0];
const teacherGroups=()=> state.role==='admin'?data.groups:data.groups.filter(g=>teacherObj().groups.includes(g.id));
const views={
 dashboard(){const v=$('#view'); const attToday=data.attendance.filter(a=>a.date===today()); v.innerHTML=`<div class="grid"><section class="card"><h3>Grupos</h3><div class="bigNumber">${data.groups.length}</div><p class="muted">Configurado para 6 grupos.</p></section><section class="card"><h3>Alumnos</h3><div class="bigNumber">${data.students.length}</div><p class="muted">Listas reales cargadas desde Excel; puedes agregar más alumnos si lo necesitas.</p></section><section class="card"><h3>Maestros</h3><div class="bigNumber">${data.teachers.length}</div><p class="muted">Cada maestro puede tener grupos asignados.</p></section><section class="card"><h3>Registros hoy</h3><div class="bigNumber">${attToday.length}</div><p class="muted">Asistencias registradas el día ${today()}.</p></section></div><section class="card"><h3>Uso rápido</h3><p>1. Administra alumnos y maestros. 2. El maestro entra a <b>Generar QR</b>. 3. Selecciona grupo, materia y horario. 4. Proyecta el QR. 5. Los estudiantes lo escanean con la cámara del celular y registran su asistencia.</p></section>`;},
 sesion(){const v=$('#view'); v.innerHTML=`<section class="card"><h3>Nueva sesión de asistencia</h3><div class="grid"><div><label>Grupo</label><select id="sessGroup">${teacherGroups().map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select></div><div><label>Materia</label><input id="sessSubject" value="Matemáticas"></div><div><label>Entrada</label><input id="sessStart" type="time" value="14:30"></div><div><label>Minutos para retardo</label><input id="sessLate" type="number" value="10"></div></div><button onclick="createSession()">Crear QR de asistencia</button></section><section id="qrBox" class="card hidden"><h3>QR de la sesión</h3><canvas id="qrCanvas"></canvas><p id="qrLink" class="small muted"></p><button class="secondary" onclick="copySessionLink()">Copiar enlace</button><button class="warn" onclick="closeSession()">Cerrar sesión</button></section>`;},
 asistencia(){const v=$('#view'); const rows=data.attendance.slice().reverse().map(a=>{const s=data.students.find(x=>x.matricula===a.matricula)||{}; const g=data.groups.find(x=>x.id===a.groupId)||{}; return `<tr><td>${a.date}</td><td>${a.time}</td><td>${a.name||s.name}</td><td>${a.matricula}</td><td>${g.name||''}</td><td><span class="pill ${a.status==='Asistencia'?'ok':a.status==='Retardo'?'warn':'bad'}">${a.status}</span></td><td>${a.teacher||''}</td></tr>`}).join(''); v.innerHTML=`<section class="card"><div class="row"><h3 style="flex:1">Registros de asistencia</h3><button onclick="exportCSV('attendance')">Exportar CSV</button></div><table><thead><tr><th>Fecha</th><th>Hora</th><th>Alumno</th><th>Matrícula</th><th>Grupo</th><th>Estado</th><th>Maestro</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Sin registros.</td></tr>'}</tbody></table></section>`;},
 alumnos(){const v=$('#view'); v.innerHTML=`<section class="card"><h3>Alta de alumno</h3><div class="grid"><div><label>Matrícula</label><input id="mat" placeholder="BIG201"></div><div><label>Nombre</label><input id="nom" placeholder="Nombre completo"></div><div><label>Grupo</label><select id="grp">${data.groups.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select></div></div><button onclick="addStudent()">Agregar alumno</button><button class="secondary" onclick="loadSampleStudents()">Restaurar listas cargadas</button></section><section class="card"><div class="row"><h3 style="flex:1">Alumnos (${data.students.length})</h3><button onclick="exportCSV('students')">Exportar alumnos</button></div><table><thead><tr><th>Matrícula</th><th>Nombre</th><th>Grupo</th><th></th></tr></thead><tbody>${data.students.map(s=>`<tr><td>${s.matricula}</td><td>${s.name}</td><td>${(data.groups.find(g=>g.id===s.groupId)||{}).name}</td><td><button class="danger" onclick="delStudent('${s.id}')">Eliminar</button></td></tr>`).join('')}</tbody></table></section>`;},
 maestros(){const v=$('#view'); if(state.role!=='admin'){v.innerHTML='<section class="card"><p>Solo el administrador puede modificar maestros.</p></section>';return} v.innerHTML=`<section class="card"><h3>Alta de maestro</h3><label>Nombre</label><input id="teacherName" placeholder="Nombre del maestro"><label>Grupos asignados</label><div class="row">${data.groups.map(g=>`<label class="small"><input type="checkbox" class="gcheck" value="${g.id}" style="width:auto"> ${g.name}</label>`).join('')}</div><button onclick="addTeacher()">Agregar maestro</button></section><section class="card"><h3>Maestros</h3><table><thead><tr><th>Nombre</th><th>Grupos</th><th></th></tr></thead><tbody>${data.teachers.map(t=>`<tr><td>${t.name}</td><td>${t.groups.map(id=>(data.groups.find(g=>g.id===id)||{}).name).join(', ')}</td><td><button class="danger" onclick="delTeacher('${t.id}')">Eliminar</button></td></tr>`).join('')}</tbody></table></section>`;},
 credenciales(){const cards=data.students.map(s=>`<div class="printCard"><b>${s.name}</b><br><span>${s.matricula}</span><br><span>${(data.groups.find(g=>g.id===s.groupId)||{}).name}</span><div id="qr_${s.id}"></div></div>`).join(''); $('#view').innerHTML=`<section class="card"><div class="row noPrint"><h3 style="flex:1">Credenciales QR de estudiantes</h3><button onclick="window.print()">Imprimir</button></div><p class="muted noPrint">Estos QR son permanentes para identificar al estudiante. También puedes usar la opción de QR dinámico por sesión.</p><div>${cards}</div></section>`; data.students.forEach(s=>{const el=document.getElementById('qr_'+s.id); QRCode.toCanvas(document.createElement('canvas'), JSON.stringify({matricula:s.matricula,name:s.name}), {width:145}, (err,canvas)=>{if(!err) el.appendChild(canvas)})});},
 reportes(){const byGroup=data.groups.map(g=>({g:g.name,n:data.attendance.filter(a=>a.groupId===g.id).length})); $('#view').innerHTML=`<section class="card"><h3>Reporte general</h3><table><thead><tr><th>Grupo</th><th>Registros acumulados</th></tr></thead><tbody>${byGroup.map(x=>`<tr><td>${x.g}</td><td>${x.n}</td></tr>`).join('')}</tbody></table><button onclick="exportCSV('attendance')">Descargar reporte CSV</button></section>`;}
};
function createSession(){const groupId=$('#sessGroup').value; const group=data.groups.find(g=>g.id===groupId); const session={id:uid(),groupId,groupName:group.name,subject:$('#sessSubject').value,teacher:state.user,start:$('#sessStart').value,late:Number($('#sessLate').value||10),date:today(),open:true}; data.sessions.push(session); save(data); const link=`${baseUrl()}#/student?session=${session.id}`; $('#qrBox').classList.remove('hidden'); QRCode.toCanvas($('#qrCanvas'),link,{width:260},()=>{}); $('#qrLink').textContent=link; if(online) db.collection('sessions').doc(session.id).set(session);}
function copySessionLink(){navigator.clipboard?.writeText($('#qrLink').textContent); alert('Enlace copiado');}
function closeSession(){const last=data.sessions[data.sessions.length-1]; if(last){last.open=false; save(data); if(online) db.collection('sessions').doc(last.id).update({open:false});} alert('Sesión cerrada');}
async function renderStudent(sessionId){const app=$('#app'); app.innerHTML=$('#studentTpl').innerHTML; let session=data.sessions.find(s=>s.id===sessionId); if(online && sessionId){const snap=await db.collection('sessions').doc(sessionId).get(); if(snap.exists) session=snap.data();}
 $('#studentSessionInfo').innerHTML=session?`<b>${session.subject}</b><br>Grupo: ${session.groupName}<br>Maestro: ${session.teacher}<br>Fecha: ${session.date}`:'No se detectó sesión. Pide al maestro volver a generar el QR.';
 $('#submitAttendance').onclick=async()=>{const matricula=$('#studentMatricula').value.trim().toUpperCase(); const name=$('#studentName').value.trim(); if(!session){$('#studentMsg').textContent='Sesión no válida.';return} if(!matricula||!name){$('#studentMsg').textContent='Escribe matrícula y nombre.';return} const student=data.students.find(s=>s.matricula.toUpperCase()===matricula); if(student && student.groupId!==session.groupId){$('#studentMsg').textContent='Tu matrícula pertenece a otro grupo. Verifica tus datos.';return} const duplicate=data.attendance.find(a=>a.sessionId===session.id && a.matricula===matricula && (a.name||'').toLowerCase()===name.toLowerCase()); if(duplicate){$('#studentMsg').textContent='Tu asistencia ya estaba registrada.';return} const minsLate=diffMinutes(session.start, nowTime()); const status=minsLate<=session.late?'Asistencia':'Retardo'; const rec={id:uid(),sessionId:session.id,date:today(),time:nowTime(),matricula,name,groupId:session.groupId,subject:session.subject,teacher:session.teacher,status}; data.attendance.push(rec); save(data); if(online) await db.collection('attendance').doc(rec.id).set(rec); $('#studentMsg').textContent='Asistencia registrada correctamente: '+status;};}
function diffMinutes(start, current){const [h,m]=start.split(':').map(Number); const d=new Date(); const s=new Date(); s.setHours(h,m,0,0); return Math.round((d-s)/60000);}
function addStudent(){data.students.push({id:uid(),matricula:$('#mat').value.trim().toUpperCase(),curp:'',sexo:'',name:$('#nom').value.trim(),groupId:$('#grp').value}); save(data); render();}
function delStudent(id){data.students=data.students.filter(s=>s.id!==id); save(data); render();}
function addTeacher(){const groups=[...document.querySelectorAll('.gcheck:checked')].map(x=>x.value); data.teachers.push({id:uid(),name:$('#teacherName').value.trim(),groups}); save(data); render();}
function delTeacher(id){data.teachers=data.teachers.filter(t=>t.id!==id); save(data); render();}
function loadSampleStudents(){data.students=JSON.parse(JSON.stringify(defaults.students)); data.groups=JSON.parse(JSON.stringify(defaults.groups)); save(data); render();}
function exportCSV(type){let rows=[]; if(type==='students') rows=[['matricula','curp','sexo','nombre','grupo'],...data.students.map(s=>[s.matricula,s.curp||'',s.sexo||'',s.name,(data.groups.find(g=>g.id===s.groupId)||{}).name])]; else rows=[['fecha','hora','alumno','matricula','grupo','materia','maestro','estado'],...data.attendance.map(a=>[a.date,a.time,a.name,a.matricula,(data.groups.find(g=>g.id===a.groupId)||{}).name,a.subject,a.teacher,a.status])]; const csv=rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${type}_${today()}.csv`; a.click();}
window.addEventListener('hashchange',render); render();
