import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";
import { getFirestore, collection, doc, setDoc, getDoc, getDocs, addDoc, deleteDoc, updateDoc, query, where, serverTimestamp, runTransaction } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";

const app = initializeApp(window.SIGE_FIREBASE_CONFIG);
const auth = getAuth(app);
const db = getFirestore(app);
const $ = (s)=>document.querySelector(s);
const appEl = $('#app');
let currentUser=null, currentProfile=null, route='dashboard';
const roles = {admin:'Administrador',teacher:'Profesor',parent:'Padre/Tutor',student:'Alumno',services:'Servicios escolares'};
const today = ()=> new Date().toISOString().slice(0,10);
const nowTime = ()=> new Date().toTimeString().slice(0,5);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function uid(){return Math.random().toString(36).slice(2,10)}
function norm(s){return (s||'').toString().trim()}
function minutes(t){const [h,m]=(t||'00:00').split(':').map(Number);return h*60+m}
async function col(name){ const snap=await getDocs(collection(db,name)); return snap.docs.map(d=>({id:d.id,...d.data()})); }
async function getGroupsForUser(){ const groups=await col('grupos'); if(!currentProfile) return []; if(currentProfile.role==='admin'||currentProfile.role==='services') return groups; if(currentProfile.role==='teacher') return groups.filter(g=>(currentProfile.groupIds||[]).includes(g.id)); return groups; }
function csvDownload(rows, filename){ const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); a.download=filename; a.click(); }
function pdfTable(title, head, body, filename){ const { jsPDF } = window.jspdf; const docu=new jsPDF('l','pt','a4'); docu.setFontSize(15); docu.text(title,40,35); docu.autoTable({head:[head],body,startY:55,styles:{fontSize:9}}); docu.save(filename); }

const setupHTML = `<section class="login"><div class="login-card"><div class="brand"><h1>SIGE BIG</h1><p>Sistema Integral de Gestión Escolar para asistencia, calificaciones, observaciones, reportes y consulta familiar.</p><p class="notice">Primer ingreso: crea la cuenta del administrador principal. Después usa correo y contraseña.</p></div><div class="login-form"><h2>Primer ingreso</h2><p class="muted">Crea el administrador principal del sistema.</p><div class="field"><label>Nombre completo</label><input id="setupName" placeholder="Eduardo Chávez"></div><div class="field"><label>Correo</label><input id="setupEmail" type="email"></div><div class="field"><label>Contraseña</label><input id="setupPass" type="password"></div><button id="createAdmin">Crear administrador</button><button class="ghost" id="showLogin">Ya tengo cuenta</button></div></div></section>`;
const loginHTML = `<section class="login"><div class="login-card"><div class="brand"><h1>SIGE BIG</h1><p>Acceso institucional por rol: administrador, profesor, padre/tutor, alumno y servicios escolares.</p></div><div class="login-form"><h2>Iniciar sesión</h2><div class="field"><label>Correo electrónico</label><input id="email" type="email"></div><div class="field"><label>Contraseña</label><input id="pass" type="password"></div><div class="row"><button id="loginBtn">Entrar</button><button class="ghost" id="resetBtn">Recuperar contraseña</button></div><hr><button class="secondary" id="showSetup">Crear administrador inicial</button></div></div></section>`;
function renderLogin(){ appEl.innerHTML=loginHTML; $('#loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('#email').value,$('#pass').value)}catch(e){toast('No se pudo iniciar sesión: '+e.message)}}; $('#resetBtn').onclick=async()=>{if(!$('#email').value)return toast('Escribe tu correo'); await sendPasswordResetEmail(auth,$('#email').value); toast('Correo de recuperación enviado')}; $('#showSetup').onclick=renderSetup; }
function renderSetup(){ appEl.innerHTML=setupHTML; $('#showLogin').onclick=renderLogin; $('#createAdmin').onclick=async()=>{try{const cred=await createUserWithEmailAndPassword(auth,$('#setupEmail').value,$('#setupPass').value); await setDoc(doc(db,'usuarios',cred.user.uid),{name:$('#setupName').value,email:$('#setupEmail').value,role:'admin',active:true,createdAt:serverTimestamp()}); await seedBase(); toast('Administrador creado')}catch(e){toast('No se pudo crear: '+e.message)}}; }
async function seedBase(){ const g=await col('grupos'); if(g.length) return; for(const name of ['3-A','3-B','3-C','4-A','4-B','4-C']) await setDoc(doc(db,'grupos',name),{name,grade:name.split('-')[0],active:true}); for(const mat of ['Matemáticas','Español','Computación','Física','Historia','Inglés']) await setDoc(doc(db,'materias',mat.toLowerCase().replaceAll(' ','-')),{name:mat,active:true}); }

onAuthStateChanged(auth, async (u)=>{ currentUser=u; if(!u){ currentProfile=null; renderLogin(); return; } const p=await getDoc(doc(db,'usuarios',u.uid)); if(p.exists()){ currentProfile={id:p.id,...p.data()}; renderShell(); return; }
  const byEmail=await getDocs(query(collection(db,'usuarios'),where('email','==',u.email)));
  if(!byEmail.empty){ const d=byEmail.docs[0]; currentProfile={id:d.id,...d.data()}; await setDoc(doc(db,'usuarios',u.uid),{...currentProfile,uid:u.uid},{merge:true}); renderShell(); return; }
  const pending=await getDocs(query(collection(db,'perfilesPendientes'),where('email','==',u.email)));
  if(!pending.empty){ const d=pending.docs[0]; currentProfile={id:d.id,...d.data()}; await setDoc(doc(db,'usuarios',u.uid),{...currentProfile,uid:u.uid},{merge:true}); renderShell(); return; }
  await setDoc(doc(db,'usuarios',u.uid),{name:u.email,email:u.email,role:'teacher',active:false,createdAt:serverTimestamp()}); currentProfile={name:u.email,email:u.email,role:'teacher',active:false}; renderShell(); });
function navItems(){ const r=currentProfile.role; const all=[['dashboard','Inicio'],['asistencia','Asistencia QR'],['reportes','Reportes'],['acumulado','Reporte acumulado'],['calificaciones','Calificaciones'],['observaciones','Observaciones'],['alumnos','Alumnos'],['usuarios','Docentes y usuarios'],['materias','Materias'],['grupos','Grupos'],['padres','Portal familiar']]; if(r==='admin') return all; if(r==='services') return all.filter(x=>!['calificaciones','observaciones','padres'].includes(x[0])); if(r==='teacher') return all.filter(x=>['dashboard','asistencia','reportes','acumulado','calificaciones','observaciones','alumnos'].includes(x[0])); if(r==='parent'||r==='student') return all.filter(x=>['padres'].includes(x[0])); return [['dashboard','Inicio']]; }
function renderShell(){ if(!currentProfile.active && currentProfile.role!=='admin') return appEl.innerHTML=`<div class="login"><div class="student-card"><h2>Cuenta pendiente</h2><p>Tu cuenta existe, pero el administrador debe activarla y asignarte rol/grupos.</p><button id="out">Salir</button></div></div>`, $('#out').onclick=()=>signOut(auth); appEl.innerHTML=`<div class="layout"><aside class="side"><h2>SIGE BIG</h2><div class="role">${currentProfile.name||currentUser.email}<br>${roles[currentProfile.role]||currentProfile.role}</div><div class="nav">${navItems().map(([id,name])=>`<button data-r="${id}" class="${route===id?'active':''}">${name}</button>`).join('')}</div><br><button class="danger" id="logout">Cerrar sesión</button></aside><section class="content"><div class="topbar"><div><h1 id="title"></h1><p class="muted">Bachillerato Integral Guanajuato</p></div></div><div id="view"></div></section></div>`; document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{route=b.dataset.r;renderShell()}); $('#logout').onclick=()=>signOut(auth); renderRoute(); }
function renderRoute(){ const title={dashboard:'Inicio',asistencia:'Asistencia QR',reportes:'Reportes diarios',acumulado:'Reporte acumulado',calificaciones:'Calificaciones',observaciones:'Observaciones',alumnos:'Alumnos',grupos:'Grupos',usuarios:'Docentes y usuarios',padres:'Portal familiar'}[route]; $('#title').textContent=title; ({dashboard,asistencia,reportes,acumulado,calificaciones,observaciones,alumnos,usuarios,materias,grupos,padres}[route]||dashboard)(); }
async function dashboard(){ const [al,gr,as,us]=await Promise.all([col('alumnos'),col('grupos'),col('asistencias'),col('usuarios')]); $('#view').innerHTML=`<div class="grid cols4"><div class="card stat"><span>Alumnos</span><b>${al.length}</b></div><div class="card stat"><span>Grupos</span><b>${gr.length}</b></div><div class="card stat"><span>Registros</span><b>${as.length}</b></div><div class="card stat"><span>Usuarios</span><b>${us.length}</b></div></div><div class="card"><h3>Accesos rápidos</h3><div class="actions"><button onclick="window.location.hash='asistencia'">Asistencia</button><button onclick="window.location.hash='reportes'">Reportes</button></div><p class="muted">Sistema conectado a Firebase. Usa el panel de administración para cargar alumnos, usuarios y grupos.</p></div>`; }

async function usuarios(){
  const [users, groups, mats] = await Promise.all([col('usuarios'), col('grupos'), col('materias')]);
  const personal = users.filter(u=>!['student'].includes(u.role));
  $('#view').innerHTML=`
  <div class="card"><h3>Docentes y miembros de la comunidad escolar</h3>
    <p class="muted">Aquí se administran administradores, docentes y servicios escolares. Para que puedan entrar, el correo también debe existir en Firebase Authentication.</p>
    <div class="grid cols3">
      <div class="field"><label>Nombre</label><input id="uName" placeholder="Nombre completo"></div>
      <div class="field"><label>Correo</label><input id="uEmail" type="email" placeholder="correo@ejemplo.com"></div>
      <div class="field"><label>Rol</label><select id="uRole"><option value="teacher">Docente</option><option value="services">Servicios escolares</option><option value="admin">Administrador</option><option value="parent">Padre/Tutor</option></select></div>
    </div>
    <div class="grid cols2">
      <div class="field"><label>Grupos asignados</label><select id="uGroups" multiple size="6">${groups.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><small>Ctrl/Cmd + clic para seleccionar varios.</small></div>
      <div class="field"><label>Materias asignadas</label><select id="uMats" multiple size="6">${mats.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select><small>Ctrl/Cmd + clic para seleccionar varias.</small></div>
    </div>
    <label class="check"><input type="checkbox" id="uAllGroups"> Asignar todos los grupos</label>
    <label class="check"><input type="checkbox" id="uActive" checked> Usuario activo</label><br>
    <button id="saveUser">Guardar docente/usuario</button>
  </div>
  <div class="card"><h3>Listado de docentes y usuarios</h3>${table(personal,['name','email','role','active','groupIds','materiaIds'],['Nombre','Correo','Rol','Activo','Grupos','Materias'],true)}</div>`;
  $('#saveUser').onclick=async()=>{
    const email=norm($('#uEmail').value); if(!email) return toast('Correo requerido');
    const id=btoa(email).replaceAll('=','').replaceAll('/','_').replaceAll('+','-');
    const selectedGroups=[...$('#uGroups').selectedOptions].map(o=>o.value);
    const selectedMats=[...$('#uMats').selectedOptions].map(o=>o.value);
    await setDoc(doc(db,'usuarios',id),{name:$('#uName').value,email,role:$('#uRole').value,active:$('#uActive').checked,groupIds:$('#uAllGroups').checked?groups.map(g=>g.id):selectedGroups,materiaIds:selectedMats,updatedAt:serverTimestamp()},{merge:true});
    toast('Usuario guardado'); usuarios();
  };
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{ if(confirm('¿Borrar este usuario del perfil del sistema? No borra la cuenta de Firebase Authentication.')){ await deleteDoc(doc(db,'usuarios',b.dataset.del)); toast('Usuario borrado'); usuarios(); }});
}
function table(data,keys,heads,actions=false){ return `<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}${actions?'<th>Acciones</th>':''}</tr></thead><tbody>${data.map(r=>`<tr>${keys.map(k=>`<td>${Array.isArray(r[k])?r[k].join(', '):(r[k]??'')}</td>`).join('')}${actions?`<td><button class="danger" data-del="${r.id}">Borrar</button></td>`:''}</tr>`).join('')}</tbody></table>`; }

async function materias(){
  const mats=await col('materias');
  $('#view').innerHTML=`<div class="card"><h3>Crear materia</h3><div class="grid cols3"><input id="mName" placeholder="Nombre de la materia"><input id="mClave" placeholder="Clave opcional"><button id="addM">Agregar materia</button></div></div><div class="card"><h3>Materias</h3>${table(mats,['name','clave','active'],['Materia','Clave','Activa'],true)}</div>`;
  $('#addM').onclick=async()=>{const n=norm($('#mName').value); if(!n)return toast('Nombre requerido'); const id=norm($('#mClave').value)||n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-'); await setDoc(doc(db,'materias',id),{name:n,clave:$('#mClave').value||id,active:true,updatedAt:serverTimestamp()},{merge:true}); toast('Materia agregada'); materias();};
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{ if(confirm('¿Eliminar materia?')){ await deleteDoc(doc(db,'materias',b.dataset.del)); toast('Materia eliminada'); materias(); }});
}

async function grupos(){
  const gs=await col('grupos');
  $('#view').innerHTML=`<div class="card"><h3>Nuevo grupo</h3><div class="grid cols3"><input id="gName" placeholder="3-A"><input id="gGrade" placeholder="Grado/Semestre"><button id="addG">Agregar grupo</button></div></div><div class="card"><h3>Grupos</h3>${table(gs,['name','grade','active'],['Grupo','Grado/Semestre','Activo'],true)}</div>`;
  $('#addG').onclick=async()=>{const n=norm($('#gName').value); if(n){await setDoc(doc(db,'grupos',n),{name:n,grade:$('#gGrade').value||n.split('-')[0],active:true,updatedAt:serverTimestamp()},{merge:true}); toast('Grupo guardado'); grupos();}};
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{ if(confirm('¿Eliminar grupo?')){ await deleteDoc(doc(db,'grupos',b.dataset.del)); toast('Grupo eliminado'); grupos(); }});
}

async function alumnos(){
  const [als,gs]=await Promise.all([col('alumnos'),getGroupsForUser()]);
  $('#view').innerHTML=`<div class="card"><h3>Alumnos</h3><p class="muted">Módulo separado para estudiantes. Aquí puedes agregar tutor y correos de contacto.</p><div class="grid cols4"><input id="aMat" placeholder="Matrícula"><input id="aNom" placeholder="Nombre completo"><select id="aGru">${gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><input id="aTutorNom" placeholder="Nombre padre/tutor"></div><div class="grid cols3"><input id="aTutor" placeholder="Correo padre/tutor"><input id="aTutor2" placeholder="Correo adicional"><input id="aAlumnoEmail" placeholder="Correo alumno opcional"></div><br><button id="addA">Agregar alumno</button></div><div class="card"><h3>Importar alumnos desde Excel/CSV</h3><input type="file" id="imp" accept=".xlsx,.xls,.csv"><p class="muted">Columnas esperadas: matricula, nombre, grupo, tutorNombre, tutorEmail, tutorEmail2, email.</p></div><div class="card"><h3>Listado de alumnos</h3>${table(als,['matricula','nombre','grupo','tutorNombre','tutorEmail','tutorEmail2','email'],['Matrícula','Nombre','Grupo','Padre/Tutor','Correo tutor','Correo adicional','Correo alumno'],true)}</div>`;
  $('#addA').onclick=async()=>{const mat=norm($('#aMat').value)||uid(); await setDoc(doc(db,'alumnos',mat),{matricula:mat,nombre:$('#aNom').value,grupo:$('#aGru').value,tutorNombre:$('#aTutorNom').value,tutorEmail:$('#aTutor').value,tutorEmail2:$('#aTutor2').value,email:$('#aAlumnoEmail').value,active:true,updatedAt:serverTimestamp()},{merge:true}); toast('Alumno guardado'); alumnos();};
  $('#imp').onchange=async(e)=>{const file=e.target.files[0]; if(!file)return; const data=await file.arrayBuffer(); const wb=XLSX.read(data); const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]); for(const r of rows){const mat=norm(r.matricula||r.Matricula||r.MATRICULA||r['Matrícula'])||uid(); await setDoc(doc(db,'alumnos',mat),{matricula:mat,nombre:r.nombre||r.Nombre||'',grupo:r.grupo||r.Grupo||'',tutorNombre:r.tutorNombre||r.TutorNombre||r['Nombre tutor']||r['Padre/Tutor']||'',tutorEmail:r.tutorEmail||r.Tutor||r['Correo tutor']||'',tutorEmail2:r.tutorEmail2||r['Correo adicional']||'',email:r.email||r.Email||r['Correo alumno']||'',active:true,updatedAt:serverTimestamp()},{merge:true});} toast('Importación terminada'); alumnos();};
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{ if(confirm('¿Borrar alumno? También dejará de aparecer en listas futuras.')){ await deleteDoc(doc(db,'alumnos',b.dataset.del)); toast('Alumno borrado'); alumnos(); }});
}

async function asistencia(){ const gs=await getGroupsForUser(); $('#view').innerHTML=`<div class="grid cols2"><div class="card"><h3>Generar QR de sesión</h3><div class="field"><label>Grupo</label><select id="sGroup">${gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select></div><div class="grid cols3"><div class="field"><label>Fecha</label><input id="sDate" type="date" value="${today()}"></div><div class="field"><label>Inicio de clase</label><input id="sStart" type="time" value="14:30"></div><div class="field"><label>Tolerancia min.</label><input id="sTol" type="number" value="10"></div></div><button id="makeSession">Crear sesión</button><p id="sessionInfo" class="muted"></p></div><div class="card"><h3>QR</h3><div id="qr" class="qrbox">Genera una sesión</div></div></div>`; $('#makeSession').onclick=async()=>{const sid=`${$('#sDate').value}_${$('#sGroup').value}_${uid()}`; await setDoc(doc(db,'sesiones',sid),{id:sid,grupo:$('#sGroup').value,fecha:$('#sDate').value,inicio:$('#sStart').value,tolerancia:Number($('#sTol').value||0),teacherId:currentUser.uid,active:true,createdAt:serverTimestamp()}); const url=location.href.split('#')[0].replace(/index\.html$/,'')+`?registro=${sid}`; $('#qr').innerHTML=''; new QRCode($('#qr'),{text:url,width:220,height:220}); $('#sessionInfo').innerHTML=`Sesión creada: <b>${sid}</b><br><a href="${url}" target="_blank">Abrir registro</a>`; }; }
async function studentRegister(sid){ const sdoc=await getDoc(doc(db,'sesiones',sid)); if(!sdoc.exists()) return appEl.innerHTML=`<div class="student-register"><div class="student-card"><h2>Sesión no encontrada</h2></div></div>`; const s=sdoc.data(); if(localStorage.getItem('bloqueo_'+sid)) return appEl.innerHTML=`<div class="student-register"><div class="student-card"><h2>Asistencia registrada</h2><p>Este dispositivo ya fue utilizado para esta sesión.</p></div></div>`; const als=(await col('alumnos')).filter(a=>a.grupo===s.grupo && a.active!==false).sort((a,b)=>a.nombre.localeCompare(b.nombre)); appEl.innerHTML=`<div class="student-register"><div class="student-card"><h2>Registro de asistencia</h2><p><b>Grupo:</b> ${s.grupo}<br><b>Fecha:</b> ${s.fecha}</p><div class="field"><label>Selecciona tu nombre</label><select id="regAlumno"><option value="">Seleccionar...</option>${als.map(a=>`<option value="${a.id}">${a.nombre}</option>`).join('')}</select></div><button id="regBtn">Registrar asistencia</button></div></div>`; $('#regBtn').onclick=async()=>{const aid=$('#regAlumno').value; if(!aid)return toast('Selecciona tu nombre'); const al=als.find(a=>a.id===aid); const hora=nowTime(); const estado=minutes(hora)<=minutes(s.inicio)?'A':(minutes(hora)<=minutes(s.inicio)+Number(s.tolerancia||0)?'TOL':'R'); const rid=`${sid}_${aid}`; try{await runTransaction(db, async(tr)=>{const ref=doc(db,'asistencias',rid); const old=await tr.get(ref); if(old.exists()) throw new Error('duplicado'); tr.set(ref,{sessionId:sid,fecha:s.fecha,grupo:s.grupo,alumnoId:aid,nombre:al.nombre,hora,estado,createdAt:serverTimestamp()});}); localStorage.setItem('bloqueo_'+sid,'1'); appEl.innerHTML=`<div class="student-register"><div class="student-card"><h2>Registro realizado</h2><p>${al.nombre}<br><b>${hora}</b></p></div></div>`;}catch(e){toast('Ya existe un registro para este alumno en esta sesión');}} }

async function reportes(){ const gs=await getGroupsForUser(); $('#view').innerHTML=`<div class="card"><h3>Reporte diario</h3><div class="grid cols4"><select id="rGroup">${gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><input id="rDate" type="date" value="${today()}"><button id="genRep">Generar</button><button id="manual">Registro manual</button></div></div><div id="repOut"></div>`; $('#manual').onclick=manualRegistro; $('#genRep').onclick=async()=>{const rows=(await col('asistencias')).filter(a=>a.grupo===$('#rGroup').value&&a.fecha===$('#rDate').value).sort((a,b)=>a.nombre.localeCompare(b.nombre)); $('#repOut').innerHTML=`<div class="card"><div class="actions"><button id="csv">CSV</button><button id="pdf">PDF</button></div>${table(rows,['fecha','grupo','nombre','hora','estado'],['Fecha','Grupo','Nombre','Hora','Estado'],true)}</div>`; document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,'asistencias',b.dataset.del)); toast('Registro borrado'); $('#genRep').click();}); $('#csv').onclick=()=>csvDownload([['Fecha','Grupo','Nombre','Hora'],...rows.map(r=>[r.fecha,r.grupo,r.nombre,r.hora])],`reporte_${$('#rGroup').value}_${$('#rDate').value}.csv`); $('#pdf').onclick=()=>pdfTable(`Reporte ${$('#rGroup').value} ${$('#rDate').value}`,['Fecha','Grupo','Nombre','Hora'],rows.map(r=>[r.fecha,r.grupo,r.nombre,r.hora]),`reporte_${$('#rGroup').value}.pdf`); }; }
async function manualRegistro(){ const group=$('#rGroup').value, fecha=$('#rDate').value; const als=(await col('alumnos')).filter(a=>a.grupo===group); $('#repOut').innerHTML=`<div class="card"><h3>Registro manual</h3><div class="grid cols3"><select id="mAlumno">${als.map(a=>`<option value="${a.id}">${a.nombre}</option>`).join('')}</select><input id="mHora" type="time" value="${nowTime()}"><button id="saveM">Guardar</button></div></div>`; $('#saveM').onclick=async()=>{const al=als.find(a=>a.id===$('#mAlumno').value); const rid=`manual_${fecha}_${group}_${al.id}`; await setDoc(doc(db,'asistencias',rid),{sessionId:'manual',fecha,grupo:group,alumnoId:al.id,nombre:al.nombre,hora:$('#mHora').value,estado:'MANUAL',createdAt:serverTimestamp()},{merge:false}).catch(()=>toast('Ya existe')); toast('Registro manual guardado');}; }
async function acumulado(){ const gs=await getGroupsForUser(); $('#view').innerHTML=`<div class="card"><h3>Reporte acumulado</h3><div class="grid cols4"><select id="acGroup">${gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><input id="from" type="date" value="${today()}"><input id="to" type="date" value="${today()}"><button id="genAc">Generar</button></div></div><div id="acOut"></div>`; $('#genAc').onclick=async()=>{const group=$('#acGroup').value; const dates=[]; let d=new Date($('#from').value+'T00:00'); const end=new Date($('#to').value+'T00:00'); while(d<=end){dates.push(d.toISOString().slice(0,10)); d.setDate(d.getDate()+1);} const als=(await col('alumnos')).filter(a=>a.grupo===group).sort((a,b)=>a.nombre.localeCompare(b.nombre)); const regs=(await col('asistencias')).filter(a=>a.grupo===group && dates.includes(a.fecha)); const body=als.map(a=>[a.nombre,...dates.map(dt=>regs.some(r=>r.alumnoId===a.id&&r.fecha===dt)?'A':'NA')]); $('#acOut').innerHTML=`<div class="card"><div class="actions"><button id="acCsv">CSV</button><button id="acPdf">PDF</button></div><div style="overflow:auto"><table><thead><tr><th>Alumno</th>${dates.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${body.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`; $('#acCsv').onclick=()=>csvDownload([['Alumno',...dates],...body],`acumulado_${group}.csv`); $('#acPdf').onclick=()=>pdfTable(`Reporte acumulado ${group}`,['Alumno',...dates],body,`acumulado_${group}.pdf`);}; }
async function calificaciones(){ const [gs,mats,als]=await Promise.all([getGroupsForUser(),col('materias'),col('alumnos')]); $('#view').innerHTML=`<div class="card"><h3>Captura de calificaciones</h3><div class="grid cols4"><select id="cGroup">${gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><select id="cMat">${mats.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select><select id="cPer"><option>Parcial 1</option><option>Parcial 2</option><option>Parcial 3</option><option>Final</option></select><button id="loadCal">Cargar</button></div></div><div id="calOut"></div>`; $('#loadCal').onclick=async()=>{const students=als.filter(a=>a.grupo===$('#cGroup').value); $('#calOut').innerHTML=`<div class="card"><table><thead><tr><th>Alumno</th><th>Calificación</th></tr></thead><tbody>${students.map(a=>`<tr><td>${a.nombre}</td><td><input type="number" min="0" max="10" step=".1" data-cal="${a.id}"></td></tr>`).join('')}</tbody></table><br><button id="saveCal">Guardar</button></div>`; $('#saveCal').onclick=async()=>{for(const inp of document.querySelectorAll('[data-cal]')){await setDoc(doc(db,'calificaciones',`${$('#cGroup').value}_${$('#cMat').value}_${$('#cPer').value}_${inp.dataset.cal}`),{grupo:$('#cGroup').value,materia:$('#cMat').value,periodo:$('#cPer').value,alumnoId:inp.dataset.cal,calificacion:Number(inp.value||0),updatedAt:serverTimestamp()});} toast('Calificaciones guardadas');};}; }
async function observaciones(){ const [gs,als]=await Promise.all([getGroupsForUser(),col('alumnos')]); $('#view').innerHTML=`<div class="card"><h3>Nueva observación</h3><div class="grid cols3"><select id="oGroup">${gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><select id="oAlumno"></select><select id="oTipo"><option>Académica</option><option>Conducta</option><option>Tareas</option><option>Reconocimiento</option></select></div><div class="field"><textarea id="oText" placeholder="Escribe la observación"></textarea></div><button id="saveObs">Guardar</button></div><div id="obsList"></div>`; function fill(){const st=als.filter(a=>a.grupo===$('#oGroup').value); $('#oAlumno').innerHTML=st.map(a=>`<option value="${a.id}">${a.nombre}</option>`).join('')} $('#oGroup').onchange=fill; fill(); $('#saveObs').onclick=async()=>{const al=als.find(a=>a.id===$('#oAlumno').value); await addDoc(collection(db,'observaciones'),{fecha:today(),grupo:$('#oGroup').value,alumnoId:al.id,nombre:al.nombre,tipo:$('#oTipo').value,texto:$('#oText').value,teacherId:currentUser.uid,createdAt:serverTimestamp()}); toast('Observación guardada');}; }
async function padres(){ const email=currentProfile.email; const als=(await col('alumnos')).filter(a=>a.tutorEmail===email || a.tutorEmail2===email || a.email===email || currentProfile.role==='admin'); $('#view').innerHTML=`<div class="card"><h3>Consulta familiar</h3><p class="muted">Información vinculada al correo: ${email}</p>${als.length?als.map(a=>`<button class="secondary" data-st="${a.id}">${a.nombre}</button>`).join(' '):'No hay alumnos vinculados.'}</div><div id="fam"></div>`; document.querySelectorAll('[data-st]').forEach(b=>b.onclick=async()=>{const id=b.dataset.st, al=als.find(x=>x.id===id); const [regs,cals,obs]=await Promise.all([col('asistencias'),col('calificaciones'),col('observaciones')]); $('#fam').innerHTML=`<div class="grid cols3"><div class="card stat"><span>Asistencias</span><b>${regs.filter(r=>r.alumnoId===id).length}</b></div><div class="card stat"><span>Calificaciones</span><b>${cals.filter(c=>c.alumnoId===id).length}</b></div><div class="card stat"><span>Observaciones</span><b>${obs.filter(o=>o.alumnoId===id).length}</b></div></div><div class="card"><h3>${al.nombre}</h3><h4>Calificaciones</h4>${table(cals.filter(c=>c.alumnoId===id),['materia','periodo','calificacion'],['Materia','Periodo','Calificación'])}<h4>Asistencia</h4>${table(regs.filter(r=>r.alumnoId===id),['fecha','grupo','hora','estado'],['Fecha','Grupo','Hora','Estado'])}<h4>Observaciones</h4>${table(obs.filter(o=>o.alumnoId===id),['fecha','tipo','texto'],['Fecha','Tipo','Observación'])}</div>`;}); }

const params=new URLSearchParams(location.search); if(params.get('registro')) studentRegister(params.get('registro'));
